#syntax=docker/dockerfile:1
FROM nginx:latest

# COPY ./nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
# COPY ./nginx/fastcgi_params /etc/nginx/fastcgi_params