version: "3.8"
    
services:
  azure_mysql:
    image: mcoutocontainerregistry.azurecr.io/azure_mysql
    container_name: azure_mysql
    volumes:
      # - data-mysql:/var/lib/mysql
      - ${WEBAPP_STORAGE_HOME}/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    command: '--default-authentication-plugin=mysql_native_password'
    # networks:
    #   - mynet  

  azure_wordpress:
    image: mcoutocontainerregistry.azurecr.io/azure_wordpress
    container_name: azure_wordpress
    volumes:
      # - data-html:/var/www/html
      # - ${WEBAPP_STORAGE_HOME}/html:/var/www/html
      # - ${WEBAPP_STORAGE_HOME}/LogFiles/php:/var/log/php
    restart: always
    expose:
      - 8082
    environment:
      WORDPRESS_DB_HOST: azure_mysql:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', '/servicewordpressics');
        define('WP_SITEURL', '/servicewordpressics');
        $_SERVER['REQUEST_URI'] = str_replace("/wp-admin/", "/servicewordpressics/wp-admin/",  $_SERVER['REQUEST_URI']);
    links:
      - azure_mysql
    depends_on:
      - azure_mysql
    networks:
      - mynet

  azure_nginx:
      image: mcoutocontainerregistry.azurecr.io/azure_nginx
      container_name: azure_nginx
      restart: always
      volumes:
        # - data-html:/var/www/html/servicewordpressics
        # - ${WEBAPP_STORAGE_HOME}/html:/var/www/html/servicewordpressics
        # - ${WEBAPP_STORAGE_HOME}/LogFiles/nginx:/var/log/nginx
      ports:
        - 80:80
      links:
        - azure_wordpress
      depends_on:
        - azure_wordpress
#       networks:
#         - mynet

# networks:
#     mynet:

# volumes:
#   data-mysql:
  # data-html:


        # define('WP_HOME', 'http://localhost/servicewordpressics');
        # define('WP_SITEURL', 'http://localhost/servicewordpressics');
# $$_SERVER['REQUEST_URI'] = '/servicewordpressics' . $$_SERVER['REQUEST_URI'];
# $$_SERVER['REQUEST_URI'] = str_replace("/wp-admin/", "/servicewordpressics/wp-admin/",  $$_SERVER['REQUEST_URI']);